config/routes.rb
Rails.application.routes.draw do
  root "employees#index"
resources :employees
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employee.rb
class Employee < ApplicationRecord
	validates :name, presence: true
	validates :age, presence: true
	validates :gender, presence: true
	validates :designation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
 def index
    @employees = Employee.all
  end
  def show
    @employee = Employee.find(params[:id])
  end
  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)

    if @employee.save
      redirect_to @employee
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  def edit
    @employee = Employee.find(params[:id])
  end

  def update
    @employee = Employee.find(params[:id])

    if @employee.update(employee_params)
      redirect_to @employee
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    redirect_to root_path, status: :see_other
  end
  
  
  private
    def employee_params
      params.require(:employee).permit(:name, :age, :gender, :designation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_with model: employee do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age %><br>
    <%= form.text_area :age %><br>
  </div>
  
  <div>
    <%= form.label :gender %><br>
    <%= form.text_area :gender %><br>
   
  </div>
  
  <div>
    <%= form.label :designation %><br>
    <%= form.text_area :designation %><br>
    
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Edit Employee</h1>

<%= render "form", employee: @employee %>

app/views/employees/index.html.erb
<h1>Employees</h1>

<ul>
  <% @employees.each do |employee| %>
    <li>
      <%= link_to employee.name, employee %>
    </li>
  <% end %>
</ul>



<%= link_to "New Employee", new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render "form", employee: @employee %>

app/views/employees/show.html.erb
<h1><%= @employee.name %></h1>

<p><%= @employee.age %></p>
<p><%= @employee.gender %></p>
<p><%= @employee.designation %></p>

<ul>
  <li><%= link_to "Edit", edit_employee_path(@employee) %></li>
  <li><%= link_to "Destroy", employee_path(@employee), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Employees</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>